version: "3.9"

services:
  mongo:
    image: mongo:6
    container_name: flask-ci-cd-app-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  flaskapp:
    build: .
    container_name: flask-ci-cd-app-flaskapp
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - FLASK_ENV=development
    depends_on:
      - mongo
    volumes:
      - .:/app   # Mount local code for live reload
    command: flask run --host=0.0.0.0 --port=5000  # Run in dev mode for auto-reload

volumes:
  mongo-data:
