services:
  flaskapp:
    build: .
    container_name: flask-ci-cd-app-flaskapp
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app   # <-- mount your local code folder
    working_dir: /app
    command: python app.py
