services:
  mongo:
    image: mongo:6
    container_name: flask-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always

  flaskapp:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"
    volumes:
      - .:/app       # Mount local code for live updates
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017
    command: flask run --host=0.0.0.0 --port=5000  # auto-reload enabled
    depends_on:
      - mongo
    restart: always

volumes:
  mongo-data:

