version: "3.9"   # optional, Docker Compose ignores this in newer versions

services:
  mongo:
    image: mongo:6
    container_name: flask-mongo-db
    ports:
      - "27017:27017"        # map MongoDB port to host
    volumes:
      - mongo-data:/data/db
    restart: always

  flaskapp:
    build: .
    container_name: flask-app
    ports:
      - "5000:5000"          # map Flask app port to host
    environment:
      - FLASK_ENV=development
      - MONGO_URI=mongodb://mongo:27017   # connect to Mongo container
    depends_on:
      - mongo
    restart: always

volumes:
  mongo-data:
