name: CI/CD for Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      - name: Add VM to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p ${{ secrets.VM_PORT }} ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_ed25519 \
             -p ${{ secrets.VM_PORT }} \
             -o StrictHostKeyChecking=no \
             ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} << 'EOF'
                cd /home/manisha/flask-ci-cd-app
                git pull origin main

                source /home/manisha/venv/bin/activate
                pip install -r requirements.txt

                systemctl --user daemon-reload
                systemctl --user restart flask-app.service
                systemctl --user status flask-app.service --no-pager
          EOF
