name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build and start Docker containers
        run: |
          cd ~/flask-ci-cd-app
          docker compose down
          docker compose up -d --build

- name: Wait for Flask app to connect to MongoDB
  run: |
    MAX_RETRIES=20
    SLEEP_TIME=5
    RETRY_COUNT=0

    while true; do
      RESPONSE=$(curl -s http://127.0.0.1:5000/)
      echo "Response from app: $RESPONSE"

      if [[ "$RESPONSE" == *"MongoDB server is successfully installed"* ]]; then
        echo "MongoDB check passed and app responded correctly."
        break
      fi

      RETRY_COUNT=$((RETRY_COUNT+1))
      if [ $RETRY_COUNT -ge $MAX_RETRIES ]; then
        echo "Expected MongoDB success message not found after $MAX_RETRIES retries!"
        exit 1
      fi

      echo "MongoDB not ready yet, retrying in $SLEEP_TIME seconds..."
      sleep $SLEEP_TIME
    done
